# Generated by Django 5.2.8 on 2025-12-26 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('education', 'Education'), ('course', 'Online Course'), ('career', 'Career')], max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blogs/')),
                ('description', models.TextField()),
                ('published_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
    ]
